on:
  push:
    branches:
      - main
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6
      - name: Clone Terraform Module
        run: git clone https://github.com/pheenoh/ghidra-terraform-module.git?ref=1.0.0
      - name: Move files
        run: mv terraform.tfvars backend.tf ghidra-terraform-module/ && cd ghidra-terraform-module
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
  create-users:
    runs-on: ubuntu-latest
    needs: [deploy-terraform]
    steps:
      run: echo "finish"
